spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Test1234
    url: jdbc:mysql://192.168.1.241:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: mq
    password: mq123
    host: 192.168.1.241
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 192.168.1.241
    database: 0
    port: 6379
    password: 123
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.1.135/